<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Authors>Luca Bottani</Authors>
    <Company>Insider contributors</Company>
    <Copyright>Copyright © 2016-2026 Luca Bottani</Copyright>
    <Product>Insider Mod Loader</Product>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/DoctorB/insider</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>
</Project>
