<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Insider.Il2CppSmokePlugin</AssemblyName>
    <RootNamespace>Insider.Il2CppSmokePlugin</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Insider.Abstractions/Insider.Abstractions.csproj" />
  </ItemGroup>
</Project>
